### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by superxuu** [aisayko/python-gtmetrix#13]
Traceback (most recent call last):
  File "D:\Program Files\JetBrains\PyCharm 2017.2.3\helpers\pydev\pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\Program Files\JetBrains\PyCharm 2017.2.3\helpers\pydev\pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:/project/PythonProjects/tem.py", line 12, in <module>
    my_test = gt.start_test(value)
  File "D:\Python27\lib\site-packages\gtmetrix\interface.py", line 83, in start_test
    return _TestObject(self.auth, **response_data)
TypeError: __init__() got an unexpected keyword argument 'credits_left'

**Comment by Dineshchitta** [comment]
+1

**Comment by hdilaver** [comment]
+1

**Comment by sourabhkt** [comment]
This seems to be working for me.

@superxuu / @Dineshchitta / @hdilaver can you please provide some more details.

**Comment by shanejones** [comment]
I am also getting this issue too. Any update?

This has also started taking credits off my API call balance too.

```
➜  gtmetrix-python python run.py
Site: under2 - Url: https://amazon.co.uk
Traceback (most recent call last):
  File "run.py", line 10, in <module>
    my_test = gt.start_test(value)
  File "/Users/shane/Library/Python/2.7/lib/python/site-packages/gtmetrix/interface.py", line 83, in start_test
    return _TestObject(self.auth, **response_data)
TypeError: __init__() got an unexpected keyword argument 'credits_left'
```

**Comment by dlopez12003** [comment]
Any update on this?

**Comment by sourabhkt** [comment]
@dlopez12003 could you please install the package from Github and try again -

```shell
pip install git+https://github.com/aisayko/python-gtmetrix
```

@aisayko This issue was fixed in https://github.com/aisayko/python-gtmetrix/pull/9 long back. can we make a new release? I would be happy to help if you need me :)
