### ISSUE TITLE
 Getting error: No module named 'settings'

### ISSUE THREAD

**Issue by austinejose1516** [aisayko/python-gtmetrix#24]
```
python3 test.py
Traceback (most recent call last):
  File "/Users/austine/Coding/together-digital/apps/technical-report/test.py", line 1, in <module>
    from gtmetrix import *
  File "/opt/homebrew/lib/python3.10/site-packages/gtmetrix/__init__.py", line 1, in <module>
    from gtmetrix.interface import *
  File "/opt/homebrew/lib/python3.10/site-packages/gtmetrix/interface.py", line 1, in <module>
    import settings
ModuleNotFoundError: No module named 'settings'
```

Can somebody help me with this please. Thanks in advance.

**Comment by xiaohongzsy** [comment]
If you want to see the directory_tree,
make sure that settings module is install,
you can do with "Package seedir"
pip install seedir,
>>>import seedir as sd
>>>path=" which folder you want to see"
>>>sd.seedir(path)
That you can printout the structure of the folder.
link:
https://earnestt1234.github.io/seedir/seedir/index.html?ref=softhints.com

**Comment by xiaohongzsy** [comment]
Or you can pip install python-settings,this module provides you easy access to your config/settings properties from all your python modules. You can see the link with:
https://pypi.org/project/python-settings/
