### ISSUE TITLE
How to use with django

### ISSUE THREAD

**Issue by thewebsitedev** [aisayko/python-gtmetrix#4]
Hello,

How can I use this with django? I am running on python 3.5.2 and django 1.9.9.

I installed it using pip with these errors:

```
Downloading/unpacking python-gtmetrix
Downloading python-gtmetrix-0.2.3.tar.gz
Running setup.py (path:/home/twd/pr.dir/eggfruit/env/build/python-gtmetrix/setup.py) egg_info for package python-gtmetrix

warning: no files found matching '*.txt'
warning: no previously-included files found matching '*.pyc'
Requirement already satisfied (use --upgrade to upgrade): requests in ./env/lib/python3.5/site-packages (from python-gtmetrix)
Installing collected packages: python-gtmetrix
Running setup.py install for python-gtmetrix

warning: no files found matching '*.txt'
warning: no previously-included files found matching '*.pyc'
Successfully installed python-gtmetrix
Cleaning up...
```

Then I tried to run it in shell but got these errors when I ran import:

```
>>> from gtmetrix import *
    Traceback (most recent call last):
     File "/home/twd/pr.dir/eggfruit/env/lib/python3.5/site-packages/django/core/management/commands/shell.py", line 69, in handle
    self.run_shell(shell=options['interface'])
  File "/home/twd/pr.dir/eggfruit/env/lib/python3.5/site-packages/django/core/management/commands/shell.py", line 61, in run_shell
    raise ImportError
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/twd/pr.dir/eggfruit/env/lib/python3.5/site-packages/gtmetrix/__init__.py", line 1, in <module>
    from gtmetrix.interface import *
  File "/home/twd/pr.dir/eggfruit/env/lib/python3.5/site-packages/gtmetrix/interface.py", line 1, in <module>
    import settings
ImportError: No module named 'settings'
```

**Comment by aisayko** [comment]
python-gtmetrix supports only Python 2.x

If you able to port this to Python 3.x please fork package and create pull request.
